# PostgreSQL. Versions 9.1 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
development:
  adapter: postgresql
  encoding: utf8
  database: d6mhr3srjuh691
  username: lngnzmhsqdlctz
  password: 28c970c161c842d1d426c1ad3f0e2b96e144f6b29c1be7dd0f1162d16550d974
  host: ec2-54-83-49-44.compute-1.amazonaws.com
  port: 5432

test:
  adapter: postgresql
  encoding: utf8
  database: d6mhr3srjuh691
  username: lngnzmhsqdlctz
  password: 28c970c161c842d1d426c1ad3f0e2b96e144f6b29c1be7dd0f1162d16550d974
  host: ec2-54-83-49-44.compute-1.amazonaws.com
  port: 5432
  
production:
  adapter: postgresql
  encoding: utf8
  database: d6mhr3srjuh691
  username: lngnzmhsqdlctz
  password: 28c970c161c842d1d426c1ad3f0e2b96e144f6b29c1be7dd0f1162d16550d974
  host: ec2-54-83-49-44.compute-1.amazonaws.com
  port: 5432
